### ISSUE TITLE
Running ACO when starting start node is given

### ISSUE THREAD

**Issue by shubhamwaghe** [rhgrant10/acopy#18]
There are many use cases when starting node is fixed. The city to start the visiting is already given and according to that the route needs to be defined. Can this use case be solved with ACO using this library?
#enhancement

**Comment by rhgrant10** [comment]
Sorry it has taken me so long to get back to you. An answer may not even be relevant for you at this point. Regardless, I'm not sure I understand your concern. The tour found by the ant is a closed loop so the starting coordinate seems irrelevant to me... am I missing something?

**Comment by rhgrant10** [comment]
I'm closing this ticket for now but please feel free to re-engage on this issue.

**Comment by shubhamwaghe** [comment]
Sure it can be closed. Back then, I was trying to solve a problem which had an analogy with TSP. I was given a starting node and had to travel all cities **without** returning to the starting city (Not a closed a loop like TSP) I was exploring if applying Ant Colony to my problem could be of any help. Thanks!

**Comment by Amalgamator** [comment]
Actually, the pants library (former) had a nodes list and the route would always start on the node you listed twice for some reason, if I remember correctly.
